---
- hosts: all
  name: all Ceph nodes
  tasks:
    - name: get Ceph repo key
      delegate_to: localhost
      become: False
      vars:
        ansible_become: False
      run_once: True
      get_url:
        url: https://download.ceph.com/keys/release.gpg
        dest: "{{ tmp_dir }}/ceph.release.gpg"
    - name: deploy Ceph repo key
      copy:
        src: "{{ tmp_dir }}/ceph.release.gpg"
        dest: /usr/share/keyrings/ceph.release.gpg
        owner: root
        group: root
        mode: 0644
    - name: add Ceph repo
      become: True
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/ceph.release.gpg] http://download.ceph.com/debian-{{ ceph_release }}/ {{ ansible_distribution_release }} main"
        filename: ceph
        state: present
    - name: install packages
      apt:
        autoremove: yes
        install_recommends: yes
        name:
          - cephadm
          - ceph-common
          - podman
          - sudo
          - curl
          - jq
          - w3m
          - psmisc
          - fio
          - expect
    - name: remove packages
      apt:
        name:
          - cloud-init
          - avahi-daemon
          - geoclue-2.0
          - xscreensaver
          - qemu-block-extra
        autoremove: yes
        state: absent
    - name: sysctl settings
      copy:
        src: ../settings/sysctl-tuning.conf
        dest: /etc/sysctl.d/ceph-tuning.conf
        owner: root
        group: root
        mode: 0644
- hosts: all
  name: Heinlein specifics
  tasks:
    - name: podman heinlein config
      copy:
        src: podman-heinlein.conf
        dest: /etc/containers/registries.conf.d/heinlein.conf
        owner: root
        group: root
        mode: 0644
    - name: generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ tmp_dir }}/id_ceph_ed25519"
        type: ed25519
        comment: "cephadm"
      delegate_to: localhost
      become: False
      vars:
        ansible_become: False
      run_once: True
    - name: copy SSH private key to first host
      delegate_to: "{{ groups['all'][0] }}"
      copy:
        src: "{{ tmp_dir }}/id_ceph_ed25519"
        dest: /etc/ceph/ceph.sshkey
        owner: root
        group: root
        mode: 0400
      run_once: True
    - name: copy SSH public key
      copy:
        src: "{{ tmp_dir }}/id_ceph_ed25519.pub"
        dest: /etc/ceph/ceph.sshpub
        owner: root
        group: root
        mode: 0444
    - name: SSH key ceph for root
      authorized_key:
        user: root
        key: "{{ lookup('file', tmp_dir + '/id_ceph_ed25519.pub') }}"
    # - name: remove local SSH keys
    #   local_action:
    #     module: ansible.builtin.file
    #     path: {{ item }}
    #     state: absent
    #   loop:
    #     - {{ tmp_dir }}/id_ceph_ed25519
    #     - {{ tmp_dir }}/id_ceph_ed25519.pub
